# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Suhas Pai
tagline:          'Suhas Pai'
description:      'All things Natural Language Processing.<br>Comings soon.'
url:              https://piesauce.com

author:
  name:           'Suhas Pai'
  url:            https://piesauce.com/

paginate:         2
google_analytics: 
bing_seo:		  
emailme:          mailto:contact@piesauce.com

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/piesauce/piesauce.github.io

tags:

github_username:  piesauce
facebook_username: 
linkedin_username: piesauce


